Somatic CNV pipeline
dbmi-bgm/cgap-pipeline-SV-somatic pull request #1
Opened 2022-05-10 16:09 UTC by dmaziec1

2022-05-11 17:03 UTC, B3rse requested changes
I think there is only that tumor/tumour in the variable name thing to change. You will have to update cwls, workflow and metaworkflow

2022-05-11 17:03 UTC, B3rse commented on cwl/ascat.cwl
> +      glob: After_correction_tumor.tumour.png
here there is tumor in the var name name but tumour in the file name, can we make this consistent one way or another? either we mirror the file name or we change all the var name to tumor, as you prefer.

2022-05-11 17:03 UTC, B3rse commented on dockerfiles/ascat/run_ascat.sh
> +Rscript $WORKDIR/ascat.R --tumor_file $tumor_file --normal_file $normal_file --gender $gender --nthreads $nthreads && gzip cnv_ascat.tsv && gzip BAF_LogR_tumor_germline.tsv || exit 1
I would split this in three commands, each one with its own exit 1. It's easier to debug if something goes wrong.

2022-05-16 15:06 UTC, B3rse approved these changes

2022-05-16 15:57 UTC, dominikglodzikhms approved these changes

2022-05-16 16:05 UTC, merged